const scriptSrcUrls = [
    "https://stackpath.bootstrapcdn.com/",
    // "https://api.tiles.mapbox.com/",
    // "https://api.mapbox.com/",
    "https://kit.fontawesome.co/",
    "https://cdnjs.cloudflare.com/",
    "https://cdn.jsdelivr.net",
    "https://cdn.jsdelivr.net",
    "https://kit.fontawesome.com",
    "https://connect.facebook.net",
    "https://js.paystack.co",
    "https://unpkg.com",
    "https://pagead2.googlesyndication.com",
    "https://www.gstatic.com",
    "https://www.googletagmanager.com",
    "https://partner.googleadservices.com",
    "https://adservice.google.com.ng",
    "https://adservice.google.com",
    "https://tpc.googlesyndication.com",
    "https://fundingchoicesmessages.google.com",
    "https://ep2.adtrafficquality.google",
    "https://checkout.flutterwave.com",
    "https://mozilla.github.io",
    "https://pl25901707.effectiveratecpm.com",
    "https://recordedthereby.com",
    "https://quickerapparently.com",
    "https://capaciousdrewreligion.com",
];
const styleSrcUrls = [
    "https://kit-free.fontawesome.com/",
    "https://stackpath.bootstrapcdn.com/",
    // "https://api.mapbox.com/",
    // "https://api.tiles.mapbox.com/",
    "https://fonts.googleapis.com/",
    "https://use.fontawesome.com/",
    "https://cdn.jsdelivr.net",
    "https://paystack.com",
    "https://cdnjs.cloudflare.com",
];
const connectSrcUrls = [
    "https://api.emailjs.com/",
    "https://ka-f.fontawesome.com",
    "https://www.facebook.com",
    "https://web.facebook.com",
    "https://graph.facebook.com",
    "https://z-p3-graph.facebook.com",
    "https://z-m-graph.facebook.com",
    "https://pagead2.googlesyndication.com",
    "https://ep1.adtrafficquality.google",
    "https://fundingchoicesmessages.google.com",
    "https://csi.gstatic.com",
    "https://firebase.googleapis.com",
    "https://firebaseinstallations.googleapis.com",
    "https://www.google-analytics.com",
    "https://google-analytics.com",
    "https://api.ravepay.co",
    "https://flw-events-ge.herokuapp.com",
    "https://experttrafficcounter.com",
    "https://nannyirrationalacquainted.com",
    // "https://api.mapbox.com/",
    // "https://a.tiles.mapbox.com/",
    // "https://b.tiles.mapbox.com/",
    // "https://events.mapbox.com/",
];
const fontSrcUrls = [
    "https://fonts.gstatic.com/",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
];
const frameSrcUrls = [
    "https://checkout.paystack.com",
    "https://checkout-v3-ui-prod.f4b-flutterwave.com",
    "https://googleads.g.doubleclick.net",
    "https://tpc.googlesyndication.com",
    "https://www.google.com",
    "https://www.youtube.com",
    "https://www.boomplay.com",
    "https://checkout.flutterwave.com",
    "https://checkout-v3-ui-prod.tls-flutterwave.com/",
]

module.exports.helmetDirectives = {
    defaultSrc: [],
    connectSrc: ["'self'", ...connectSrcUrls],
    scriptSrc: ["'unsafe-inline'", "'self'", ...scriptSrcUrls],
    styleSrc: ["'self'", "'unsafe-inline'", ...styleSrcUrls],
    workerSrc: ["'self'", "blob:"],
    frameSrc: ["*","'self'", "data:", "blob:", ...frameSrcUrls],
    objectSrc: [],
    mediaSrc: [
        "'self'", 
        "https://youtu.be", 
        "https://www.youtube.com",
        "https://godinprintsdocuments.s3.amazonaws.com",
    ],
    imgSrc: [
        "'self'",
        "blob:",
        "data:",
        "*.amazonaws.com",
        "https://freepngimg.com",
        "https://i.swncdn.com",
        "https://dailymanna.dclm.org",
        "https://www.abideinchrist.com",
        "https://www.hymnlyrics.org",
        "https://ghs.deeperlifesermons.com.ng",
        "https://biblemenus.com/bh14.png",
        "https://www.bible.com",
        "https://tpc.googlesyndication.com",
        "https://www.kingjamesbibleonline.org",
        "https://www.biblereward.com",
        "https://www.christianityboard.com",
        "https://www.christianforums.com",
        "https://dclm.org",
        "https://www.facebook.com",
        "https://www.google.com",
        "en.wikipedia.org",
        "*",

        // "https://res.cloudinary.com/depvtmznu/", //SHOULD MATCH YOUR CLOUDINARY ACCOUNT! 
        // "https://images.unsplash.com/",
    ],
    fontSrc: ["'self'", ...fontSrcUrls],
}